print.summarytools <- function(x, method="pander", silent = FALSE, footer = FALSE,
                               file = "", append = FALSE, report.title = NA, 
                               group.only = FALSE, escape.pipe = FALSE, ...) {

  if (!method %in% c("pander", "browser", "viewer", "html_file"))
    stop("method must be one of 'pander', 'browser', 'viewer' or 'html_file'")
  
  if (file == "" && isTRUE(append))
    stop("append is set to TRUE but no file name has been specified")
  
  if (file != "" && isTRUE(append) && !file.exists(file))
    stop("append is set to TRUE but specified file does not exist")
  
  if (file != "" && isTRUE(append) && !is.na(report.title))
    message("Appending existing file -- 'report.title' argument will be ignored")

  # override x's attributes if any are passed as additional arguments
  argslst <- match.call()
  
  if ("date" %in% names(argslst))
    attr(x, "date") <- argslst$date
  if ("style" %in% names(argslst))
    attr(x, "pander.args")['style'] <- argslst$style
  if ("round" %in% names(argslst))
    attr(x, "pander.args")['round'] <- argslst$round
  if ("round.digits" %in% names(argslst))
    attr(x, "pander.args")['round'] <- argslst$round.digits
  if ("justify" %in% names(argslst))
    attr(x, "pander.args")['justify'] <- argslst$justify
  if ("plain.ascii" %in% names(argslst))
    attr(x, "pander.args")['plain.ascii'] <- argslst$plain.ascii
  if ("split.table" %in% names(argslst))
    attr(x, "pander.args")['split.table'] <- argslst$split.table
  if ("Label" %in% names(argslst))
    attr(x, "var.info")['Label'] <- argslst$Label
  if ("Subset" %in% names(argslst))
    attr(x, "var.info")['Subset'] <- argslst$Subset
  if ("Group" %in% names(argslst))
    attr(x, "var.info")['by.group'] <- argslst$Group
  if ("Weights" %in% names(argslst))
    attr(x, "var.info")['Weights'] <- argslst$Weights
  
  # When style is 'rmarkdown', make plain.ascii FALSE unless specified explicitly
  if (method == "pander" && attr(x, "pander.args")$style == 'rmarkdown' && 
      isTRUE(attr(x, "pander.args")$plain.ascii) && (!"plain.ascii" %in% (names(match.call())))) {
    plain.ascii <- FALSE
  }
  
  if (isTRUE(group.only) && !"by.group" %in% names (attributes(x)))
    stop("group.only can only be used with objects created using by()")
  
  # Function to add '#' in non-plain-ascii pander tables
  addHash <- function(str, n=4) {
    if (isTRUE(attr(x, "pander.args")$plain.ascii))
      str
    else
      paste(paste0(rep(x = "#", times = n), collapse = ""), str)
  }
  
  if (method %in% c("browser", "viewer", "html_file")) {
    stpath <- find.package("summarytools")
    
    # build footer note
    fnote <- paste0("Generated by <a href='https://github.com/dcomtois/summarytools'>summarytools</a> package version ",
                    packageVersion(pkg = "summarytools"),
                    " (<a href='http://www.r-project.org/'>R</a> version ", getRversion(), ")",
                    "<br/>", Sys.Date())
  }
  
  # Build 3 "info" elements: out.info, var.info (same as out.info but excludes Group), 
  # and gr.info (Group alone)
  if ("var.info" %in% names(attributes(x))) {
    tmp <- attr(x, "var.info")
    out.info <- tmp[which(!is.na(tmp))]
    var.info <- tmp[which(!is.na(tmp) && names(tmp) != "Group")]
    gr.info <- tmp['Group']
    rm(tmp)
    
    if(method=="pander") {
      out.info <- paste(addHash(names(out.info)), out.info, sep=": ", collapse="\n")
      var.info <- paste(addHash(names(var.info)), var.info, sep=": ", collapse="\n")
      if (!is.na(gr.info))
        gr.info <- paste(addHash("Group: "), gr.info)
    } else {
      var.info <- as.matrix(paste(names(var.info), var.info, sep=": "))
      if (!is.na(gr.info))
        gr.info <- paste("Group: ", gr.info)
    }
    
  } else {
    out.info <- NA
    var.info <- NA
    gr.info <- NA
  }
  
  # printing freq objects -----------------------------------------------------
  if(attr(x, "st.type") == "freq") {
    
    # define section title
    stitle <- ifelse("Weights" %in% names(attr(x, "var.info")),
                     "Weighted Frequencies",
                     "Frequencies")
    
    if(method == "pander") {
      
      if (!isTRUE(group.only))
        cat("\n", addHash(stitle, 3), "\n\n", out.info, sep = "", 
            file = file, append = append)
      else 
        cat("\n", gr.info, sep = "", 
            file = file, append = append)

      cat(do.call(pander::pander, append(attr(x, "pander.args"), list(x = quote(x)))), 
          file = file, append = append)
    
    } else {

      # method = viewer / browser / html_file ------------------------------
      freq.table.html <-
        xtable::print.xtable(xtable::xtable(x = x, align = "rccccc",
                                            digits = c(0,
                                                       attr(x, "pander.args")$round * as.numeric("weights" %in% names(attributes(x))),
                                                       rep(attr(x, "pander.args")$round, 4))),
                             type = "html", print.results = FALSE,
                             html.table.attributes = 'class="table table-striped table-bordered"')
      
      freq.table.html <- gsub("<td> ", "<td>", freq.table.html)

      doc_div <- tags$div(class="container",
                          if (!isTRUE(group.only)) 
                            h2(stitle),
                          if (!isTRUE(group.only)) 
                            h4(var.info),
                          if (!is.na(gr.info))
                            h5(gr.info),
                          br(),
                          HTML(text = gsub("<td> ", "<td>", freq.table.html)),
                          if (isTRUE(footer))
                            HTML(text = fnote))
      
    }
  }

  # printing ctable objects -----------------------------------------------------
  if(attr(x, "st.type") == "ctable") {
    
    stitle <- "Cross-Tabulation"
    if(attr(x, "prop.type") %in% c("r", "c", "t")) {
      c_table <- paste0(x$ctable,
                        sub(pattern = "\\((\\d[\\.\\%])", replacement = "( \\1", 
                            x = sprintf(paste0(" (%.", attr(x, "round.digits"), "f%%)"), x$prop*100)))
      c_table <- matrix(c_table, nrow = nrow(x$ctable), 
                        dimnames = dimnames(x$ctable), byrow = FALSE)
    } else {
      c_table <- x$ctable
    }
    
    if(method == "pander") {
      
      if (!isTRUE(group.only)) 
        cat("\n", addHash(stitle, 3), "\n", file = file, append = append)
      
      cat("\n", addHash(paste(names(dimnames(x$ctable)), collapse = " X "), 4), "\n",
          addHash("Proportions: ", 4), switch(attr(x, "prop.type"), r="Rows", c="Columns", t="Total"),
          sep = "", file = file, append = append)
      
      cat(do.call(pander::pander, append(attr(x, "pander.args"), list(x = ftable(c_table)))),
          file = file, append = append)
      
    } else {
      
      # method = viewer / browser  ------------------------------
      dnn <- names(dimnames(c_table))
      addtorow <- list()
      addtorow$pos <- list(0, 0)
      colnames(c_table)[colnames(c_table)=="<NA>"] <- "&lt;NA&gt;"
      addtorow$command <- c(paste0('<tr> <th> </th> <th colspan=', ncol(c_table)-1,'>',dnn[2],'</th><th></th></tr>'),
                            paste0('<tr> <th>', dnn[1], '</th> <th>', 
                                   paste(colnames(c_table), collapse = "</th> <th>"),
                                   '</th></tr>'))
      
      ctable.html <-
        xtable::print.xtable(xtable::xtable(x = c_table,
                                            align = paste0("r", paste(rep("c", ncol(c_table)),
                                                                      collapse=""))),
                             type = "html", print.results = FALSE,
                             add.to.row = addtorow, include.colnames = FALSE,
                             html.table.attributes = 'class="table table-striped table-bordered"')

      doc_div <- tags$div(class="container",
                          if (!isTRUE(group.only)) 
                            h2(stitle),
                          if (!isTRUE(group.only)) 
                            h4(var.info),
                          if (!is.na(gr.info))
                            h5(gr.info),
                          br(),
                          HTML(text = gsub("<td> ", "<td>", ctable.html)),
                          if (isTRUE(footer))
                            HTML(text = fnote))
    }
  }
  
  # Printing descr objects ----------------------------------------------------
  if(attr(x, "st.type") == "descr") {

    if(!silent && "ignored" %in% names(attributes(x)))
      message("Non-numerical variable(s) ignored: ", attr(x, "ignored"))
    
    stitle <- ifelse("Weights" %in% names(attr(x, "var.info")),
                     "Weighted Descriptive Statistics",
                     "Descriptive Statistics")
    
    if(method=="pander") {
      if (!isTRUE(group.only))
        cat("\n", addHash(stitle, 3), "\n", out.info, sep = "", 
            file = file, append = append)
      else
        cat("\n", gr.info, sep = "", 
            file = file, append = append)
      
      cat(do.call(pander::pander, append(attr(x, "pander.args"), list(x=quote(x$stats)))),
            file = file, append = append)
      
      cat(addHash("Observations"), file = file, append = append)
      
      cat(do.call(pander::pander, append(attr(x, "pander.args"), list(x=quote(x$observ)))),
          file = file, append = append)
      
    } else {
      
      # method = viewer / browser / html_file --------------------------
      descr.table.html <-
        xtable::print.xtable(xtable::xtable(x = x$stats,
                                            align = paste0("r", paste(rep("c",ncol(x$stats)),
                                                                     collapse="")),
                                            digits = c(0,rep(attr(x, "pander.args")$round,
                                                             ncol(x$stats)))),
                             type = "html", print.results = FALSE,
                             html.table.attributes = 'class="table table-striped table-bordered"')

      obs.table.html <-
        xtable::print.xtable(xtable::xtable(x = x$observ, align = paste0("r", paste(rep("c",ncol(x$observ)),collapse="")),
                                            digits = c(0,rep(attr(x, "pander.args")$round,ncol(x$observ)))),
                             type = "html", print.results = FALSE,
                             html.table.attributes = 'class="table table-striped table-bordered"')

      doc_div <- tags$div(class="container",
                          if (!isTRUE(group.only))
                            h2(stitle),
                          if (!isTRUE(group.only))
                            h4(var.info),
                          if (!is.na(gr.info))
                            h5(gr.info),
                          br(),
                          HTML(text = gsub("<td> ", "<td>", descr.table.html)),
                          h5("Observations"),
                          HTML(gsub("<td> ", "<td>", obs.table.html)),
                          if (isTRUE(footer))
                            HTML(text = fnote))
    }
  }

  # Printing dfSummary objects ------------------------------------------------
  if(attr(x, "st.type") == "dfSummary") {
    
    stitle <- "Dataframe Summary"
    
    if(method=="pander") {
      
      cat("\n", addHash(stitle, 3), "\n", sep = "", 
          file = file, append = append)
      cat("\n", addHash(attr(x, "df.name"), 4), "\n", sep = "", 
          file = file, append = append)
      cat(do.call(pander::pander, append(attr(x, "pander.args"), list(x=quote(x)))), 
          file = file, append = append)
      
    } else {

      # method = viewer / browser --------------------------------
      dfSummary.html <-
        xtable::print.xtable(xtable::xtable(x = x,digits = 0,
                                            align = paste0("c", paste(rep("l",ncol(x)),collapse=""))),
                             include.rownames = FALSE, type = "html", print.results = FALSE,
                             sanitize.colnames.function = function(x) gsub("\\.", " ", x),
                             html.table.attributes = 'class="table table-striped table-bordered"')

      doc_div <- tags$div(class="container",
                          h2(stitle),
                          h3(attr(x, "df.name")),
                          if("rows.subset" %in% names(attributes(x)$out.info))
                            p("Rows subset:", attr(x,"subset")),
                          h4("Number of rows: ", attr(x, "n.obs")),
                          br(),
                          HTML(gsub("<td> ", "<td>", dfSummary.html)),
                          if (isTRUE(footer))
                            HTML(text = fnote))
    }
  }

  # Put together output file content  --------------------------------------------
  if(method %in% c('browser', 'viewer', 'html_file')) {
    
    if (isTRUE(append)) {
        f <- file(file, open = "r")
        htmlcontent <- paste(readLines(f, warn = FALSE, encoding = "UTF-8"), collapse="\n")
        close(f)
        top_part <- sub("(^.+)(</body>.+)", "\\1", htmlcontent)
        bottom_part <- sub("(^.+)(</body>.+)", "\\2", htmlcontent)
        insert_part <- iconv(as.character(doc_div), "", "UTF-8")
        htmlcontent <- paste(top_part, insert_part, bottom_part, sep = "\n")
        
    } else {
        
      htmlcontent <-
        tags$html(
          tags$header(
            tags$meta(charset="UTF-8"),
            tags$title(ifelse(is.na(report.title), stitle, report.title)),
            includeCSS(path = paste(stpath,"includes/stylesheets/bootstrap.min.css", sep="/")),
            includeCSS(path = paste(stpath,"includes/stylesheets/custom.css", sep="/"))
          ),
          tags$body(doc_div)
        )
      
      htmlcontent <- paste("<!DOCTYPE html>", iconv(as.character(htmlcontent), "", "UTF-8"), sep = "\n")
    }
    
    outfile <- ifelse(file == "", paste0(tempfile(),".html"), file)
    #if(file.exists(file))
    #  unlink(file)
    #capture.output(cat(htmlcontent), file = outfile, append = append)
    capture.output(cat(htmlcontent), file = outfile)

    if(method=="viewer") {
      if(.Platform$GUI == "RStudio") 
        rstudioapi::viewer(outfile)
      else {
        message("Method 'viewer' only valid within RStudio. Switching method to 'browser'.")
        method <- "browser"
      }
    }
    
    # For method "browser", we don't use utils::browseURL() because of compatibility issues with RStudio
    if(method=="browser") {
      switch(Sys.info()[['sysname']],
             Windows = {shell.exec(file = paste0("file:///", outfile))},
             Linux   = {system(paste('/usr/bin/xdg-open', outfile), wait = FALSE, ignore.stdout = TRUE)},
             Darwin  = {system(paste('open', outfile), wait = FALSE, ignore.stderr = TRUE)})
    }
    
    # return file path and update tmpfiles vector when method = browser or viewer ----------------------
    if(method %in% c("browser", "viewer") && file == "") {
      if(!silent)
        message(paste0("Temporary file created: ", outfile, '\nTo delete, use cleartmp().'))
      .st.env$tmpfiles <- c(.st.env$tmpfiles, outfile)
      return(invisible(normalizePath(outfile)))
    } else if (method == "html_file") {
      return(invisible(normalizePath(outfile, mustWork = FALSE)))
    } else {
      return(invisible())
    }
  }
}
